spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hzero
    password: hzero
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 956740304@qq.com
    password: 18395586365jwx
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 2MB
  resources:
    static-locations: classpath:/static/,file:/static/

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # \u6570\u636E\u5E93\u4E0B\u5212\u7EBF\u8F6C\u9A7C\u5CF0\u914D\u7F6E
    mapUnderscoreToCamelCase: true

choerodon:
  resource:
    pattern: /v1/*
    
logging:
  level:
    org.apache.ibatis: ${LOGGING_LEVEL:debug}
    io.choerodon: ${LOGGING_LEVEL:debug}
    org.hzero: ${LOGGING_LEVEL:debug}
    com.hand6.health.infra: debug
    com.hand6.health.infra.mapper: debug